-- MySQL Script generated by MySQL Workbench
-- 01/24/19 12:51:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csem_controle_de_ponto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csem_controle_de_ponto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csem_controle_de_ponto` DEFAULT CHARACTER SET utf8 ;
USE `csem_controle_de_ponto` ;

-- -----------------------------------------------------
-- Table `csem_controle_de_ponto`.`PontoMes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csem_controle_de_ponto`.`PontoMes` (
  `idPontoMes` INT NOT NULL AUTO_INCREMENT,
  `somaHoraTrabalhada` VARCHAR(45) NULL,
  `somaHoraExtra` VARCHAR(45) NULL,
  `saldo` VARCHAR(45) NULL,
  `mes` INT NULL,
  `ano` INT NULL,
  PRIMARY KEY (`idPontoMes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csem_controle_de_ponto`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csem_controle_de_ponto`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cargo` VARCHAR(45) NULL,
  `jornadaDeTrabalho` TIME NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csem_controle_de_ponto`.`Ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csem_controle_de_ponto`.`Ponto` (
  `idPonto` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NULL,
  `entrada` TIME NULL,
  `saidaIntervalo` TIME NULL,
  `entradaIntervalo` TIME NULL,
  `saida` TIME NULL,
  `horasTrabalhadasDia` TIME NULL,
  `horasExtrasTotalDia` VARCHAR(45) NULL,
  `horaExtraDia` MEDIUMTEXT NULL,
  `minutoExtraDia` MEDIUMTEXT NULL,
  `motivo` VARCHAR(100) NULL,
  `fkPontoMes` INT NOT NULL,
  `fkFuncionario` INT NOT NULL,
  PRIMARY KEY (`idPonto`),
  INDEX `fk_Ponto_PontoMes_idx` (`fkPontoMes` ASC),
  INDEX `fk_Ponto_Funcionario1_idx` (`fkFuncionario` ASC),
  CONSTRAINT `fk_Ponto_PontoMes`
    FOREIGN KEY (`fkPontoMes`)
    REFERENCES `csem_controle_de_ponto`.`PontoMes` (`idPontoMes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ponto_Funcionario1`
    FOREIGN KEY (`fkFuncionario`)
    REFERENCES `csem_controle_de_ponto`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csem_controle_de_ponto`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csem_controle_de_ponto`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
